version: "3"
services:
#   Enables resolving container hostnames from host machine
  dns-media:
    image: defreitas/dns-proxy-server:2.19.0-arm8x64
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

  unique-id-service:
    image: mjgiardino/media-microservices:xenial
    hostname: unique-id-service
    ports:
      - 10001:9090
    restart: always
    entrypoint: UniqueIdService
    depends_on:
      - nginx-web-server

  movie-id-service:
    image: mjgiardino/media-microservices:xenial
    hostname: movie-id-service
    restart: always
    entrypoint: MovieIdService
    depends_on:
      - nginx-web-server    

  movie-id-mongodb:
    image: mongo:4.4.6
    hostname: movie-id-mongodb
    restart: always

  movie-id-memcached:
    image: memcached
    hostname: movie-id-memcached
    restart: always

  text-service:
    image: mjgiardino/media-microservices:xenial
    hostname: text-service
    restart: always
    entrypoint: TextService
    depends_on:
      - nginx-web-server      

  rating-service:
    image: mjgiardino/media-microservices:xenial
    hostname: rating-service
    restart: always
    entrypoint: RatingService
    depends_on:
      - movie-id-service

  rating-redis:
    image: redis
    hostname: rating-redis
    restart: always
    
  user-service:
    image: mjgiardino/media-microservices:xenial
    hostname: user-service
    restart: always
    entrypoint: UserService
    depends_on:
      - nginx-web-server

  user-mongodb:
    image: mongo:4.4.6
    hostname: user-mongodb
    restart: always

  user-memcached:
    image: memcached
    hostname: user-memcached
    restart: always

  compose-review-service:
    image: mjgiardino/media-microservices:xenial
    hostname: compose-review-service
    ports:
      - 10006:9090
    restart: always
    entrypoint: ComposeReviewService
    depends_on:
      - movie-id-service
      - rating-service
      - unique-id-service
      - user-service
      - text-service
    deploy:
      replicas: $b

  compose-review-memcached:
    image: memcached
    hostname: compose-review-memcached
    restart: always

  review-storage-service:
    image: mjgiardino/media-microservices:xenial
    hostname: review-storage-service
    restart: always
    entrypoint: ReviewStorageService
    depends_on:
      - compose-review-service

  review-storage-mongodb:
    image: mongo:4.4.6
    hostname: review-storage-mongodb
    restart: always

  review-storage-memcached:
    image: memcached
    hostname: review-storage-memcached
    restart: always

  user-review-service:
    image: mjgiardino/media-microservices:xenial
    hostname: user-review-service
    restart: always
    entrypoint: UserReviewService
    depends_on:
      - compose-review-service
      
  user-review-mongodb:
    image: mongo:4.4.6
    hostname: user-review-mongodb
    restart: always

  user-review-redis:
    image: redis
    hostname: user-review-redis
    restart: always

  movie-review-service:
    image: mjgiardino/media-microservices:xenial
    hostname: movie-review-service
    restart: always
    entrypoint: MovieReviewService
    depends_on:
      - compose-review-service

  movie-review-mongodb:
    image: mongo:4.4.6
    hostname: movie-review-mongodb
    ports:
      - 27022:27017
    restart: always

  movie-review-redis:
    image: redis
    hostname: movie-review-redis
    restart: always

  nginx-web-server:
    image: mjgiardino/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    volumes:
      - /home/phablet/DeathStarBench/mediaMicroservices/nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - /home/phablet/DeathStarBench/mediaMicroservices/nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /home/phablet/DeathStarBench/mediaMicroservices/nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - /home/phablet/DeathStarBench/mediaMicroservices/gen-lua:/gen-lua
    deploy:
      replicas: $a
  cast-info-service:
    image: mjgiardino/media-microservices:xenial
    hostname: cast-info-service
    restart: always
    entrypoint: CastInfoService
    depends_on:
      - nginx-web-server

  cast-info-mongodb:
    image: mongo:4.4.6
    hostname: cast-info-mongodb
    restart: always

  cast-info-memcached:
    image: memcached
    hostname: cast-info-memcached
    restart: always

  plot-service:
    image: mjgiardino/media-microservices:xenial
    hostname: plot-service
    restart: always
    entrypoint: PlotService
    depends_on:
      - nginx-web-server

  plot-mongodb:
    image: mongo:4.4.6
    hostname: plot-mongodb
    restart: always

  plot-memcached:
    image: memcached
    hostname: plot-memcached
    restart: always

  movie-info-service:
    image: mjgiardino/media-microservices:xenial
    hostname: movie-info-service
    restart: always
    entrypoint: MovieInfoService
    depends_on:
      - nginx-web-server

  movie-info-mongodb:
    image: mongo:4.4.6
    hostname: movie-info-mongodb
    restart: always

  movie-info-memcached:
    image: memcached
    hostname: movie-info-memcached
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
